### PR TITLE
Add "mentions" badge

### PR DESCRIPTION
**Pull request by DenisGorbachev**
Hi Rob,

Sending a PR with the badge as promised. Right now it's a static version - just wanted to release it as soon as possible :)

Does it look good?

### CODE REVIEW

**Comment by robrich** [comment]
I like it, though it seems like we need to push it further to make it golden.  Do you need help with a domain name and https cert for this?  What's your timeline for a non-static version?  I'd love to spread this around to my other packages as well.  What's your thoughts on renaming?

**Comment by DenisGorbachev** [comment]
"dependents" is the most technically correct term. However, it's already used by [NPM](https://www.npmjs.com/) + a similar term "dependencies" is used by [David](https://david-dm.org/) for another purpose.

Other names that come to mind are "users", "references", "mentions". All those have slightly different connotations - neither is perfect, but we have to choose one. "Mentions" has a good balance of being short while still technically correct (after all, the package is mentioned in package.json files). That's why I chose it.

Do you have any other suggestions for the name? I'll get the domain & cert as soon as we settle on it.

P.S. The timeline for dynamic version is "a few days" - currently downloading all package.json files from GitHub :)

**Comment by DenisGorbachev** [comment]
@robrich Do you have any thoughts on the name? (or should I just get mentions-badge.com and proceed?)

**Comment by robrich** [comment]
I'm thinking "github mentions" or "github references" or "github dependencies" to help indicate that it's a github search that harvests the number.

**Comment by DenisGorbachev** [comment]
Actually, we'll be parsing package.json files directly instead of using search; in addition, we'll be parsing GitLab and Bitbucket public repositories as well, so we can't tie the badge name specifically to Github...

OK, let's just take mentions-badge.com - we can always change it later if the need arises.

**Pull request closed without merging**
